- hosts: all
  user: root
  tasks:
    - name: copy the GHOST script to the machine
      copy: src=GHOST.c dest=/tmp/GHOST.c
 
    - name: compile it 
      raw: gcc /tmp/GHOST.c -o /tmp/GHOST

    - name: run it!
      raw: /tmp/GHOST
      register: ghost

    - name: show me the results
      debug: var=ghost.stdout_lines[0]
